// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/doggos.proto

/*
Package doggos is a generated protocol buffer package.

It is generated from these files:
	proto/doggos.proto

It has these top-level messages:
	Doggo
	NewDoggoRequest
	GetDoggoRequest
	DeleteDoggoRequest
	DeleteDoggoResponse
	ListDoggosRequest
	ListDoggosResponse
*/
package doggos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Doggo struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age  uint32 `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
}

func (m *Doggo) Reset()                    { *m = Doggo{} }
func (m *Doggo) String() string            { return proto.CompactTextString(m) }
func (*Doggo) ProtoMessage()               {}
func (*Doggo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Doggo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Doggo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Doggo) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type NewDoggoRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  uint32 `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *NewDoggoRequest) Reset()                    { *m = NewDoggoRequest{} }
func (m *NewDoggoRequest) String() string            { return proto.CompactTextString(m) }
func (*NewDoggoRequest) ProtoMessage()               {}
func (*NewDoggoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewDoggoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewDoggoRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetDoggoRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *GetDoggoRequest) Reset()                    { *m = GetDoggoRequest{} }
func (m *GetDoggoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDoggoRequest) ProtoMessage()               {}
func (*GetDoggoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetDoggoRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetDoggoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteDoggoRequest struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteDoggoRequest) Reset()                    { *m = DeleteDoggoRequest{} }
func (m *DeleteDoggoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDoggoRequest) ProtoMessage()               {}
func (*DeleteDoggoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteDoggoRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteDoggoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteDoggoResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteDoggoResponse) Reset()                    { *m = DeleteDoggoResponse{} }
func (m *DeleteDoggoResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDoggoResponse) ProtoMessage()               {}
func (*DeleteDoggoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteDoggoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListDoggosRequest struct {
}

func (m *ListDoggosRequest) Reset()                    { *m = ListDoggosRequest{} }
func (m *ListDoggosRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDoggosRequest) ProtoMessage()               {}
func (*ListDoggosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ListDoggosResponse struct {
	Doggos []*Doggo `protobuf:"bytes,1,rep,name=doggos" json:"doggos,omitempty"`
}

func (m *ListDoggosResponse) Reset()                    { *m = ListDoggosResponse{} }
func (m *ListDoggosResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDoggosResponse) ProtoMessage()               {}
func (*ListDoggosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListDoggosResponse) GetDoggos() []*Doggo {
	if m != nil {
		return m.Doggos
	}
	return nil
}

func init() {
	proto.RegisterType((*Doggo)(nil), "doggos.Doggo")
	proto.RegisterType((*NewDoggoRequest)(nil), "doggos.NewDoggoRequest")
	proto.RegisterType((*GetDoggoRequest)(nil), "doggos.GetDoggoRequest")
	proto.RegisterType((*DeleteDoggoRequest)(nil), "doggos.DeleteDoggoRequest")
	proto.RegisterType((*DeleteDoggoResponse)(nil), "doggos.DeleteDoggoResponse")
	proto.RegisterType((*ListDoggosRequest)(nil), "doggos.ListDoggosRequest")
	proto.RegisterType((*ListDoggosResponse)(nil), "doggos.ListDoggosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Doggos service

type DoggosClient interface {
	CreateNewDoggo(ctx context.Context, in *NewDoggoRequest, opts ...grpc.CallOption) (*Doggo, error)
	GetDoggo(ctx context.Context, in *GetDoggoRequest, opts ...grpc.CallOption) (*Doggo, error)
	DeleteDoggo(ctx context.Context, in *DeleteDoggoRequest, opts ...grpc.CallOption) (*DeleteDoggoResponse, error)
	ListDoggos(ctx context.Context, in *ListDoggosRequest, opts ...grpc.CallOption) (*ListDoggosResponse, error)
}

type doggosClient struct {
	cc *grpc.ClientConn
}

func NewDoggosClient(cc *grpc.ClientConn) DoggosClient {
	return &doggosClient{cc}
}

func (c *doggosClient) CreateNewDoggo(ctx context.Context, in *NewDoggoRequest, opts ...grpc.CallOption) (*Doggo, error) {
	out := new(Doggo)
	err := grpc.Invoke(ctx, "/doggos.Doggos/CreateNewDoggo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doggosClient) GetDoggo(ctx context.Context, in *GetDoggoRequest, opts ...grpc.CallOption) (*Doggo, error) {
	out := new(Doggo)
	err := grpc.Invoke(ctx, "/doggos.Doggos/GetDoggo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doggosClient) DeleteDoggo(ctx context.Context, in *DeleteDoggoRequest, opts ...grpc.CallOption) (*DeleteDoggoResponse, error) {
	out := new(DeleteDoggoResponse)
	err := grpc.Invoke(ctx, "/doggos.Doggos/DeleteDoggo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doggosClient) ListDoggos(ctx context.Context, in *ListDoggosRequest, opts ...grpc.CallOption) (*ListDoggosResponse, error) {
	out := new(ListDoggosResponse)
	err := grpc.Invoke(ctx, "/doggos.Doggos/ListDoggos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Doggos service

type DoggosServer interface {
	CreateNewDoggo(context.Context, *NewDoggoRequest) (*Doggo, error)
	GetDoggo(context.Context, *GetDoggoRequest) (*Doggo, error)
	DeleteDoggo(context.Context, *DeleteDoggoRequest) (*DeleteDoggoResponse, error)
	ListDoggos(context.Context, *ListDoggosRequest) (*ListDoggosResponse, error)
}

func RegisterDoggosServer(s *grpc.Server, srv DoggosServer) {
	s.RegisterService(&_Doggos_serviceDesc, srv)
}

func _Doggos_CreateNewDoggo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewDoggoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoggosServer).CreateNewDoggo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doggos.Doggos/CreateNewDoggo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoggosServer).CreateNewDoggo(ctx, req.(*NewDoggoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doggos_GetDoggo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoggoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoggosServer).GetDoggo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doggos.Doggos/GetDoggo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoggosServer).GetDoggo(ctx, req.(*GetDoggoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doggos_DeleteDoggo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDoggoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoggosServer).DeleteDoggo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doggos.Doggos/DeleteDoggo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoggosServer).DeleteDoggo(ctx, req.(*DeleteDoggoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Doggos_ListDoggos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDoggosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoggosServer).ListDoggos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/doggos.Doggos/ListDoggos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoggosServer).ListDoggos(ctx, req.(*ListDoggosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doggos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "doggos.Doggos",
	HandlerType: (*DoggosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewDoggo",
			Handler:    _Doggos_CreateNewDoggo_Handler,
		},
		{
			MethodName: "GetDoggo",
			Handler:    _Doggos_GetDoggo_Handler,
		},
		{
			MethodName: "DeleteDoggo",
			Handler:    _Doggos_DeleteDoggo_Handler,
		},
		{
			MethodName: "ListDoggos",
			Handler:    _Doggos_ListDoggos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/doggos.proto",
}

func init() { proto.RegisterFile("proto/doggos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0x87, 0xd3, 0xa2, 0x08, 0x43, 0xf8, 0x37, 0x98, 0x58, 0xab, 0x07, 0xb2, 0x89, 0x09, 0xe1,
	0x40, 0x23, 0xc6, 0x68, 0x34, 0x9e, 0x24, 0xf1, 0x42, 0x38, 0xf4, 0xe0, 0xd9, 0x0a, 0x93, 0xa6,
	0x09, 0x76, 0x91, 0x5d, 0xf4, 0x60, 0xbc, 0xf8, 0x0a, 0x3e, 0x9a, 0x2f, 0xe0, 0xc1, 0x07, 0x31,
	0x6c, 0x77, 0x29, 0xb4, 0x1c, 0xf4, 0xb6, 0xd3, 0x99, 0xdf, 0x37, 0x9b, 0x6f, 0x0b, 0x38, 0x9b,
	0x73, 0xc9, 0xbd, 0x09, 0x0f, 0x43, 0x2e, 0x7a, 0xaa, 0xc0, 0x62, 0x52, 0xb9, 0xc7, 0x21, 0xe7,
	0xe1, 0x94, 0xbc, 0x60, 0x16, 0x79, 0x41, 0x1c, 0x73, 0x19, 0xc8, 0x88, 0xc7, 0x7a, 0x8a, 0xdd,
	0xc0, 0xee, 0x60, 0x39, 0x87, 0x35, 0xb0, 0xa3, 0x89, 0x63, 0xb5, 0xad, 0x4e, 0xd5, 0xb7, 0xa3,
	0x09, 0x22, 0xec, 0xc4, 0xc1, 0x13, 0x39, 0x76, 0xdb, 0xea, 0x94, 0x7d, 0x75, 0xc6, 0x06, 0x14,
	0x82, 0x90, 0x9c, 0x82, 0x1a, 0x5a, 0x1e, 0xd9, 0x05, 0xd4, 0x47, 0xf4, 0xaa, 0x08, 0x3e, 0x3d,
	0x2f, 0x48, 0xc8, 0x55, 0xd0, 0xca, 0x07, 0xed, 0x34, 0x78, 0x0e, 0xf5, 0x3b, 0x92, 0x1b, 0xc1,
	0x3f, 0xdc, 0x80, 0x5d, 0x02, 0x0e, 0x68, 0x4a, 0x92, 0xfe, 0x9d, 0xf4, 0xa0, 0xb5, 0x91, 0x14,
	0x33, 0x1e, 0x0b, 0x42, 0x07, 0xf6, 0xc4, 0x62, 0x3c, 0x26, 0x21, 0x54, 0xbe, 0xe4, 0x9b, 0x92,
	0xb5, 0xa0, 0x39, 0x8c, 0x44, 0x72, 0x45, 0xa1, 0x37, 0xb1, 0x6b, 0xc0, 0xf5, 0x8f, 0x1a, 0x72,
	0x02, 0x5a, 0xb6, 0x63, 0xb5, 0x0b, 0x9d, 0x4a, 0xbf, 0xda, 0xd3, 0x2f, 0x91, 0xec, 0xd2, 0xcd,
	0xfe, 0xb7, 0x0d, 0xc5, 0x24, 0x89, 0x23, 0xa8, 0xdd, 0xce, 0x29, 0x90, 0x64, 0xec, 0xe1, 0x81,
	0xc9, 0x64, 0x7c, 0xba, 0x9b, 0x30, 0xb6, 0xff, 0xf1, 0xf5, 0xf3, 0x69, 0xd7, 0x58, 0xf9, 0xe5,
	0x54, 0xbf, 0xf7, 0x95, 0xd5, 0xc5, 0x21, 0x94, 0x8c, 0xce, 0x94, 0x94, 0x11, 0x9c, 0x25, 0x39,
	0x8a, 0x84, 0xd8, 0x58, 0x91, 0xbc, 0xb7, 0xa5, 0xaa, 0x77, 0x7c, 0x80, 0xca, 0x9a, 0x2b, 0x74,
	0x57, 0xb9, 0x9c, 0x7a, 0xf7, 0x68, 0x6b, 0x2f, 0xf1, 0x62, 0x36, 0x74, 0xf3, 0x1b, 0xee, 0x01,
	0x52, 0x8f, 0x78, 0x68, 0x20, 0x39, 0xe1, 0xae, 0xbb, 0xad, 0xa5, 0xf1, 0x4d, 0x85, 0xaf, 0x60,
	0xaa, 0xe2, 0xb1, 0xa8, 0xfe, 0xea, 0xb3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xb0, 0x6e,
	0xf5, 0x11, 0x03, 0x00, 0x00,
}
